{
    "openapi": "3.1.0",
    "info": {
        "title": "Infobip OpenAPI Specification",
        "description": "OpenAPI Specification that contains all public endpoints and webhooks.",
        "contact": {
            "name": "Infobip support",
            "email": "support@infobip.com"
        },
        "version": "2.0.504",
        "x-generatedAt": "2024-10-25T09:27:29.201404901Z"
    },
    "servers": [
        {
            "url": "https://api.infobip.com"
        }
    ],
    "tags": [
        {
            "name": "channels",
            "description": "Create a perfect customer experience by using the channels your customer already use and love.\n",
            "x-type": "category",
            "x-displayName": "Channels"
        },
        {
            "name": "whatsapp",
            "description": "With 2 billion users, WhatsApp is the most used application worldwide. It enables you to reach more customers, sharing important and timely notifications, as well as provide real-time customer support. Infobip is an official WhatsApp Business solution provider. Send and manage WhatsApp messages over Infobip's WhatsApp API.\n\nTo utilize WhatsApp in combination with other channels, check out [Messages API](https://www.infobip.com/docs/api/platform/messages-api).\n\n[Learn more about WhatsApp channel and use cases](https://www.infobip.com/docs/whatsapp).\n",
            "x-type": "product",
            "x-displayName": "WhatsApp"
        },
        {
            "name": "whatsapp-outbound-messages",
            "description": "When you send a WhatsApp message to a phone number belonging to an end user's device you are sending an outbound WhatsApp message. \nThere are several types of WhatsApp messages:\n  - Template message – use a pre-defined template to send text, images, videos, share location, documents, attach buttons, and configure SMS failover.\n  - Free-form text or media – use it only when contacted by the end user within a certain timeframe to send text, images, audio, video, stickers, share location, or contacts.\n  - Interactive messages – send a message that your end user can interact with, such as interactive buttons, lists, or product messages.\n",
            "x-type": "module",
            "x-displayName": "Outbound messages"
        },
        {
            "name": "whatsapp-template-message",
            "description": "",
            "x-type": "section",
            "x-displayName": "Template Message"
        },
        {
            "name": "whatsapp-text-and-media-messages",
            "description": "",
            "x-type": "section",
            "x-displayName": "Text and media messages"
        },
        {
            "name": "send-whatsapp-interactive-messages",
            "description": "",
            "x-type": "section",
            "x-displayName": "Interactive messages"
        },
        {
            "name": "whatsapp-inbound-messages",
            "description": "When the end user sends a WhatsApp from their device to a phone number, they have sent an inbound WhatsApp message. \nThe inbound message is routed to the Infobip Platform and Infobip in turn routes the message to its customer who has registered the WhatsApp sender.\nTypical supporting features you’d use with inbound messages are:\n  - Marking messages as read to communicate to the end user that you have read their message.\n  - Downloading media and its metadata sent over by the end user.\n",
            "x-type": "module",
            "x-displayName": "Inbound messages"
        },
        {
            "name": "whatsapp-receive-inbound-message",
            "description": "",
            "x-type": "section",
            "x-displayName": "Receive inbound message"
        },
        {
            "name": "whatsapp-get-inbound-media",
            "description": "",
            "x-type": "section",
            "x-displayName": "Get inbound media"
        },
        {
            "name": "whatsapp-mark-message-as-read",
            "description": "",
            "x-type": "section",
            "x-displayName": "Mark message as read"
        },
        {
            "name": "whatsapp-message-status-reports",
            "description": "Status Reports tell you what happened to the WhatsApp message you sent, whether it was successfully delivered or failed to be delivered, whether it’s been seen. \nStatus Reports can be pushed in real time to a customer's webhook or can be retrieved by an API call. \nLogs provide similar information to Status Reports but are only available to query for 48hrs.\nThere are a few reports you can set up for your WhatsApp messaging:\n  - Delivery Reports - In case of a failure, you’ll receive a timestamp with a delivery failure message and a status code indicating the reason behind it.\n  - Seen Reports – In case the message has been delivered successfully to the end user, this report will additionally inform you whether the message has been seen.\n  - Payments - It provides all updates to your payment transaction in real time. It's also possible to fetch current state of the payment transaction in any time.\n",
            "x-type": "module",
            "x-displayName": "Message Status Reports"
        },
        {
            "name": "whatsapp-status-reports",
            "description": "",
            "x-type": "section",
            "x-displayName": "Status Reports"
        },
        {
            "name": "whatsapp-payments",
            "description": "",
            "x-type": "section",
            "x-displayName": "Payments"
        },
        {
            "name": "whatsapp-service-management",
            "description": "As opposed to free-form messages, template messages can be sent and delivered at any time. \nHere, you can manage your templates, from template registration, retrieving template statuses, to deleting existing templates.\nWith each WhatsApp message, you can send various types of media. Here, you can manage your media and configure additional feature enhancing their functionality.\nMoreover you can fetch quality and business info of your senders.\n",
            "x-type": "module",
            "x-displayName": "Service Management"
        },
        {
            "name": "whatsapp-template-management",
            "description": "",
            "x-type": "section",
            "x-displayName": "Template Management"
        },
        {
            "name": "whatsapp-flow-management",
            "description": "",
            "x-type": "section",
            "x-displayName": "Flow Management"
        },
        {
            "name": "whatsapp-media-management",
            "description": "",
            "x-type": "section",
            "x-displayName": "Media Management"
        },
        {
            "name": "whatsapp-sender-management",
            "description": "",
            "x-type": "section",
            "x-displayName": "Sender Management"
        },
        {
            "name": "whatsapp-bulk-sender-registration",
            "description": "",
            "x-type": "section",
            "x-displayName": "Bulk Sender Registration"
        },
        {
            "name": "whatsapp-identity-management",
            "description": "Set up identity change, an add-on available for senders hosted by Infobip. This is supported for interactive buttons, interactive lists, or an interactive product message. \nIdentity change allows you to increase your security by preventing messages from being sent to unverified end users. \nOnce enabled for a sender, you would receive notifications when an end user's WhatsApp account (MSISDN) has potentially been transferred to a different user. \nWhen a potential identity change has been detected, the outbound traffic towards that end user is blocked until you verify the user outside the channel and acknowledge the change.\nContact your Account Executive for more information.\n",
            "x-type": "module",
            "x-displayName": "Identity Management"
        },
        {
            "name": "whatsapp-ad-conversions",
            "description": "The Conversions API for Business Messaging enables advertisers to consolidate web, app, physical store, and business messaging events into a single endpoint for Meta. With Infobip, you can submit Purchase or LeadSubmitted conversion events for WhatsApp.\n",
            "x-type": "module",
            "x-displayName": "Ad Conversions"
        }
    ],
    "paths": {
        "/whatsapp/1/message/text": {
            "post": {
                "tags": [
                    "channels",
                    "whatsapp",
                    "whatsapp-outbound-messages",
                    "whatsapp-text-and-media-messages"
                ],
                "summary": "Send WhatsApp text message",
                "description": "Send a text message to a single recipient. Text messages can only be successfully delivered if the recipient has contacted the business within the last 24 hours, otherwise [template message](#channels/whatsapp/send-whatsapp-template-message) should be used. <br/> The API response will not contain the final delivery status, use [Delivery Reports](#channels/whatsapp/receive-whatsapp-delivery-reports) instead.",
                "externalDocs": {
                    "description": "Learn more about WhatsApp channel and use cases",
                    "url": "https://www.infobip.com/docs/whatsapp"
                },
                "operationId": "send-whatsapp-text-message",
                "requestBody": {
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.TextMessage"
                            },
                            "examples": {
                                "Text message": {
                                    "value": {
                                        "from": "441134960000",
                                        "to": "441134960001",
                                        "messageId": "a28dd97c-1ffb-4fcf-99f1-0b557ed381da",
                                        "content": {
                                            "text": "Some text"
                                        },
                                        "callbackData": "Callback data",
                                        "notifyUrl": "https://www.example.com/whatsapp",
                                        "urlOptions": {
                                            "shortenUrl": true,
                                            "trackClicks": true,
                                            "trackingUrl": "https://example.com/click-report",
                                            "removeProtocol": true,
                                            "customDomain": "example.com"
                                        }
                                    }
                                },
                                "Text message with previewable url": {
                                    "value": {
                                        "from": "441134960000",
                                        "to": "441134960001",
                                        "messageId": "a28dd97c-1ffb-4fcf-99f1-0b557ed381da",
                                        "content": {
                                            "text": "Some text with url: http://example.com",
                                            "previewUrl": true
                                        },
                                        "callbackData": "Callback data",
                                        "notifyUrl": "https://www.example.com/whatsapp",
                                        "urlOptions": {
                                            "shortenUrl": true,
                                            "trackClicks": true,
                                            "trackingUrl": "https://example.com/click-report",
                                            "removeProtocol": true,
                                            "customDomain": "example.com"
                                        }
                                    }
                                }
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "200": {
                        "description": "Message accepted for delivery",
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.SingleMessageInfo"
                                },
                                "examples": {
                                    "Success Response": {
                                        "value": {
                                            "to": "441134960001",
                                            "messageCount": 1,
                                            "messageId": "a28dd97c-1ffb-4fcf-99f1-0b557ed381da",
                                            "status": {
                                                "groupId": 1,
                                                "groupName": "PENDING",
                                                "id": 7,
                                                "name": "PENDING_ENROUTE",
                                                "description": "Message sent to next instance"
                                            }
                                        }
                                    }
                                }
                            }
                        }
                    }
                }
            }
        }
    },
    "components": {
        "schemas": {
            "f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.TextMessage": {
                "type": "object",
                "properties": {
                    "from": {
                        "type": "string",
                        "description": "Registered WhatsApp sender number. Must be in international format and comply with [WhatsApp's requirements](https://www.infobip.com/docs/whatsapp/get-started#phone-number-what-you-need-to-know).",
                        "maxLength": 24,
                        "minLength": 1
                    },
                    "to": {
                        "type": "string",
                        "description": "Message recipient number. Must be in international format.",
                        "maxLength": 24,
                        "minLength": 1
                    },
                    "messageId": {
                        "type": "string",
                        "description": "The ID that uniquely identifies the message sent.",
                        "maxLength": 100,
                        "minLength": 0
                    },
                    "content": {
                        "$ref": "#/components/schemas/f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.TextContent"
                    },
                    "callbackData": {
                        "type": "string",
                        "description": "Custom client data that will be included in a [Delivery Report](#channels/whatsapp/receive-whatsapp-delivery-reports).",
                        "maxLength": 4000,
                        "minLength": 0
                    },
                    "notifyUrl": {
                        "type": "string",
                        "description": "The URL on your callback server to which delivery and seen reports will be sent. [Delivery report format](#channels/whatsapp/receive-whatsapp-delivery-reports), [Seen report format](#channels/whatsapp/receive-whatsapp-seen-reports).",
                        "maxLength": 2048,
                        "minLength": 0
                    },
                    "urlOptions": {
                        "$ref": "#/components/schemas/f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.UrlOptions"
                    },
                    "entityId": {
                        "type": "string",
                        "description": "Required for entity use in a send request for outbound traffic. Returned in notification events. For more details, see our [documentation](https://www.infobip.com/docs/cpaas-x/application-and-entity-management).",
                        "maxLength": 255,
                        "minLength": 0
                    },
                    "applicationId": {
                        "type": "string",
                        "description": "Required for application use in a send request for outbound traffic. Returned in notification events. For more details, see our [documentation](https://www.infobip.com/docs/cpaas-x/application-and-entity-management).",
                        "maxLength": 255,
                        "minLength": 0
                    }
                },
                "required": [
                    "content",
                    "from",
                    "to"
                ]
            },
            "f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.TextContent": {
                "type": "object",
                "description": "The content object to build a message that will be sent.",
                "properties": {
                    "text": {
                        "type": "string",
                        "description": "Content of the message being sent.",
                        "maxLength": 4096,
                        "minLength": 1
                    },
                    "previewUrl": {
                        "type": "boolean",
                        "description": "Allows for URL preview from within the message. If set to `true`, the message content must contain a URL starting with `https://` or `http://`. Defaults to `false`."
                    }
                },
                "required": [
                    "text"
                ]
            },
            "f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.UrlOptions": {
                "type": "object",
                "description": "Sets up [URL shortening](https://www.infobip.com/docs/url-shortening) and tracking feature.",
                "properties": {
                    "shortenUrl": {
                        "type": "boolean",
                        "default": true,
                        "description": "Enable shortening of the URLs within a message. Set this to `true`, if you want to set up other URL options."
                    },
                    "trackClicks": {
                        "type": "boolean",
                        "default": true,
                        "description": "Enable tracking of short URL clicks within a message: which URL was clicked, how many times, and by whom."
                    },
                    "trackingUrl": {
                        "type": "string",
                        "description": "The URL of your callback server on to which the Click report will be sent."
                    },
                    "removeProtocol": {
                        "type": "boolean",
                        "default": false,
                        "description": "Remove a protocol, such as `https://`, from links to shorten a message. Note that some mobiles may not recognize such links as a URL."
                    },
                    "customDomain": {
                        "type": "string",
                        "description": "Select a predefined custom domain to use when generating a short URL."
                    }
                }
            },
            "f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.SingleMessageInfo": {
                "type": "object",
                "properties": {
                    "to": {
                        "type": "string",
                        "description": "The destination address of the message.",
                        "example": "385977666618"
                    },
                    "messageCount": {
                        "type": "integer",
                        "format": "int32",
                        "description": "Number of messages required to deliver.",
                        "example": 1
                    },
                    "messageId": {
                        "type": "string",
                        "description": "The ID that uniquely identifies the message sent. If not passed, it will be automatically generated and returned in a response.",
                        "example": "06df139a-7eb5-4a6e-902e-40e892210455"
                    },
                    "status": {
                        "$ref": "#/components/schemas/f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.SingleMessageStatus"
                    }
                }
            },
            "f30d78c250ad1209aef755ddde02bb131e1749b705985f0e9f1b007c900b98e2.SingleMessageStatus": {
                "type": "object",
                "description": "Indicates the [status](https://www.infobip.com/docs/essentials/response-status-and-error-codes#api-status-codes) of the message and how to recover from an error should there be any.",
                "properties": {
                    "groupId": {
                        "type": "integer",
                        "format": "int32",
                        "description": "Status group ID.",
                        "example": 1
                    },
                    "groupName": {
                        "type": "string",
                        "description": "Status group name.",
                        "example": "PENDING"
                    },
                    "id": {
                        "type": "integer",
                        "format": "int32",
                        "description": "Status ID.",
                        "example": 7
                    },
                    "name": {
                        "type": "string",
                        "description": "Status name.",
                        "example": "PENDING_ENROUTE"
                    },
                    "description": {
                        "type": "string",
                        "description": "Human-readable description of the status.",
                        "example": "Message sent to next instance"
                    },
                    "action": {
                        "type": "string",
                        "description": "Action that should be taken to eliminate the error."
                    }
                }
            },
            "a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.ReferralMedia": {
                "type": "object",
                "anyOf": [
                    {
                        "$ref": "#/components/schemas/a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.ReferralMediaImage"
                    },
                    {
                        "$ref": "#/components/schemas/a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.ReferralMediaVideo"
                    }
                ],
                "description": "Media information of included referral.",
                "properties": {
                    "type": {
                        "$ref": "#/components/schemas/a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.MediaType"
                    },
                    "discriminator": {
                        "propertyName": "type",
                        "mapping": {
                            "IMAGE": "#/components/schemas/a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.ReferralMediaImage",
                            "VIDEO": "#/components/schemas/a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.ReferralMediaVideo"
                        }
                    },
                    "readOnly": false,
                    "writeOnly": true
                }
            },
            "a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.ReferralMediaImage": {
                "type": "object",
                "properties": {
                    "type": {
                        "$ref": "#/components/schemas/a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.MediaType"
                    },
                    "url": {
                        "type": "string",
                        "description": "URL that leads to the image that end user saw and clicked.",
                        "readOnly": false,
                        "writeOnly": true
                    }
                }
            },
            "a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.MediaType": {
                "type": "string",
                "enum": [
                    "IMAGE",
                    "VIDEO"
                ],
                "title": "Type"
            },
            "a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.ReferralMediaVideo": {
                "type": "object",
                "properties": {
                    "type": {
                        "$ref": "#/components/schemas/a4e0c51a24a360282e1a40c61554d239555404b786d84603912030fc4cdbb512.MediaType"
                    },
                    "url": {
                        "type": "string",
                        "description": "URL that leads to the video that end user saw and clicked.",
                        "readOnly": false,
                        "writeOnly": true
                    }
                }
            }
        }
    }
}